<?php  
	define('RUTA','http://localhost/curso_php/Luis/practicas/blog');
	$db_config=array(
		'basedatos'=>'curso_php',
		'usuario'=>'root',
		'pass'=>'luis0216');
	$blog_config=array(
		'post_por_pagina'=>'2',
		'carpeta_imagenes'=>'imagenes/');
	$blog_admin=array(
		'usuario'=>'luis',
		'password'=>'luis0216');
?>